### ISSUE TITLE
madouqu 削刮无法移动文件

### ISSUE THREAD

**Issue by pkr5277** [sqzw-x/mdcx#131]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备
- [X] 我正在使用最新版本

### 描述你的问题

削刮之后报错
Traceback (most recent call last):
  File "models\core\scraper.py", line 335, in _scrape_exec_thread
  File "models\core\scraper.py", line 240, in _scrape_one_file
  File "models\core\nfo.py", line 103, in write_nfo
TypeError: replace() argument 2 must be str, not int

 [Failed] Reason: c1oreMain error: replace() argument 2 must be str, not int

但是归类成功里已有对于文件夹和图片，只有视频没被移动

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by sqzw-x** [comment]
应该和 #130 是一个问题
