### ISSUE TITLE
打开软件，cv2报错

### ISSUE THREAD

**Issue by chenxiaolong818** [sqzw-x/mdcx#219]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备

### 你使用版本的 commit hash

MDCx-win-120240127
MDCx-120240321-windows-x86_64-ecaf015e
MDCx-daily_release-windows-x86_64-daff1787

### 描述你的问题

打开软件就弹窗报错啊。三个版本都试过了，以前老版本就正常打开（MDCx-win-20230617）。报错提示如下：
Traceback (most recent call last):
  File "main.py", line 13, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "controllers\main_window\main_window.py", line 14, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "controllers\cut_window.py", line 10, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "models\core\file.py", line 18, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "models\core\utils.py", line 10, in <module>
  File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI30242\cv2\__init__.py", line 181, in <module>
    bootstrap()
  File "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI30242\cv2\__init__.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "importlib\__init__.py", line 127, in import_module
ImportError: DLL load failed while importing cv2: 找不到指定的模块。

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

**Comment by chenxiaolong818** [comment]
@northsea4 老哥，不是哦。我复制打开，发现是这个目录：C:\Users\Administrator\AppData\Local\Temp\_MEI53962，感觉像是Administrator的缩写。这个目录下有cv2文件夹。我测试了win10、win11（两个都是虚拟机）都是同样的情况，无法加载cv2。不过用实体机，win11测试，就正常了。。。。。这是啥情况呀，老哥。

**Comment by chenxiaolong818** [comment]
老哥，源码运行，是不是就是运行压缩包里面的main.py程序？运行了下，说是缺少一些包 @northsea4 ，我是小白啊，求教

**Comment by chenxiaolong818** [comment]
老哥，我解决了。有两个地方，第一个是系统缺少MFPlat.DLL、MF.dll、MFReadWrite.dll；第二个是修改cv为最新的版本：opencv-contrib-python-headless-4.10.0.84。两步缺一不可，终于可以打开了。。。。。 @northsea4
