### ISSUE TITLE
刮削成功或失败或取消，目标文件夹内容被全部删除

### ISSUE THREAD

**Issue by jessperform** [sqzw-x/mdcx#227]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备

### 你使用版本的 commit hash

120240321，以及最近的2个版本

### 描述你的问题

mac m1，系统14.5，文件在外置硬盘
MDCx，在7月6日刮削一切正常
7月10日出现此问题，刮削结束（包括成功、失败、取消）后文件丢失。
更换硬盘问题依旧
重新给予全盘控制权限问题依旧
更换MDCx其他版本（降级）问题依旧

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 相关 Logs

```Text
Create log file: /Users/#####/.mdcx/Log/2024-07-15-11-15-56.txt

 🛠 当前配置：/Users/#####/MDCx/通用.ini 加载完成！
 📂 程序目录：/Users/#####/.mdcx 
 📂 刮削目录：/Volumes/#####/未整理/selected 
 💠 刮削模式：正常模式 · 字段优先 
 🖥️ 系统信息：macOS-14.5-arm64-arm-64bit 
 🐰 软件版本：#####240321 

 ❌ JavDb 未填写 Cookie，影响 FC2 刮削！可在「设置」-「网络」添加！
基于 MDC-GUI 修改 · 当前版本: #####240321 （ <font color="green">你使用的是最新版本！🎉 </font>）
================================================================================
 ❌ ThePornDB 未填写 API Token，影响欧美刮削！可在「设置」-「网络」添加！
 ✅ JavBus 连接正常！
 🛠 当前配置：/Users/#####/MDCx/通用.ini 保存完成！
 📂 程序目录：/Users/#####/.mdcx 
 📂 刮削目录：/Volumes/#####/未整理/test bug 
 💠 刮削模式：正常模式 · 字段优先 
 🖥️ 系统信息：macOS-14.5-arm64-arm-64bit 
 🐰 软件版本：#####240321 

 🛠 当前配置：/Users/#####/MDCx/通用.ini 保存完成！
 📂 程序目录：/Users/#####/.mdcx 
 📂 刮削目录：/Volumes/#####/未整理/test bug 
 💠 刮削模式：正常模式 · 字段优先 
 🖥️ 系统信息：macOS-14.5-arm64-arm-64bit 
 🐰 软件版本：#####240321 


 ⏰ Start time: 2024-07-15 11:25:09
 🖥 Movie path: /Volumes/#####/未整理/test bug
 🔎 Searching all videos, Please wait...
    Done!!! Found (2)! Skip successfully scraped (0) repeat softlink (0)! (0s) 　
 📺 Find 2 movies
 🕷 开启多线程，线程数量（2），线程延时（10）秒...
<font color="brown"> 🍯 间歇刮削 已启用，连续刮削 10 个文件后，将自动休息 60 秒...</font>
 🕷 11:25:09 开始刮削：1/2 #####-C.mp4
 ⏱ 11:25:09（9）秒后开始刮削：2/2 #####-C.mp4
 🕷 11:25:18 开始刮削：2/2 #####-C.mp4

1/2 (50.00%) round(1) #####-C.mp4
================================================================================
 🙈 [Movie] /Volumes/#####/未整理/test bug/#####-C.mp4
 🚘 [Number] #####
 🌐 [website] attackers(4s) -> airav_cc[zh_cn](2s) -> iqqtv[jp](1s) -> avsex(1s) -> lulubar(2s) -> jav321(1s) -> javbus(1s) -> freejavbt(1s)
    🌐 attackers
       搜索地址: https://attackers.net/search/list?keyword=##### 
       番号地址: https://attackers.net/works/detail/##### 
       数据获取成功！
    🟢 标题 获取成功！(attackers)
     ↳ #####
    🌐 airav[cn]
       搜索地址: https://airav.io/cn/searchresults.aspx?Search=#####&Type=0 
       搜索结果: 未匹配到番号！ 
    🌐 iqqtv[jp]
       搜索地址: https://iqq5.xyz/jp/search.php?kw=##### 
       搜索结果: 未匹配到番号！ 
    🌐 avsex
       搜索地址: https://paycalling.com/tw/search?query=##### 
       网络请求错误: https://paycalling.com/tw/search?query=#####
Error: Failed to perform, ErrCode: 35, Reason: 'Recv failure: Connection reset by peer'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.  
    🌐 lulubar
       搜索地址: https://lulubar.co/video/bysearch?search=#####&page=1 
       网络请求错误: 403 https://lulubar.co/video/bysearch?search=#####&page=1 
    🔴 中文标题 获取失败！
    🟢 简介 获取成功！(attackers)
     ↳ #####。 
    🔴 中文简介 获取失败！
    🟢 演员 获取成功！(attackers)
     ↳ ##### 
    🟢 背景图 获取成功！(attackers)
     ↳ https://cdn.up-timely.com/image/15/content/#####/#####_2.jpg 
    🟢 封面图 获取成功！(attackers)
     ↳ https://cdn.up-timely.com/image/15/content/#####/#####_1.jpg 
    🟢 剧照 获取成功！(attackers)
     ↳ ['https://cdn.up-timely.com/image/15/content/#####/#####_3.jpg', 'https://cdn.up-timely.com/image/15/content/#####/#####_4.jpg', 'https://cdn.up-timely.com/image/15/content/#####/#####_5.jpg', 'https://cdn.up-timely.com/image/15/content/#####/#####_6.jpg', 'https://cdn.up-timely.com/image/15/content/#####/#####_7.jpg', 'https://cdn.up-timely.com/image/15/content/#####/#####_8.jpg', 'https://cdn.up-timely.com/image/15/content/#####/#####_9.jpg', 'https://cdn.up-timely.com/image/15/content/#####/#####_10.jpg', 'https://cdn.up-timely.com/image/15/content/#####/#####_11.jpg', 'https://cdn.up-timely.com/image/15/content/#####/#####_12.jpg', 'https://cdn.up-timely.com/image/15/content/#####/#####_13.jpg', 'https://cdn.up-timely.com/image/15/content/#####/#####_14.jpg'] 
    🟢 标签 获取成功！(attackers)
     ↳ ##### 
    🟢 发行日期 获取成功！(attackers)
     ↳ 2021-9-7 
    🟢 时长 获取成功！(attackers)
     ↳ 130  
    🌐 jav321
       搜索地址: https://www.jav321.com/search {"sn": #####}
       番号地址: https://www.jav321.com/video/##### 
       数据获取成功！
    🟢 评分 获取成功！(jav321)
     ↳ 4.0 
    🟢 导演 获取成功！(attackers)
     ↳ #####  
    🌐 javbus
       番号地址: https://www.javbus.com/##### 
       数据获取成功！
    🌐 freejavbt
       番号地址: https://freejavbt.com/##### 
       数据获取失败: 番号标题不存在！
    🔴 系列 获取失败！
    🟢 片商 获取成功！(javbus)
     ↳ アタッカーズ 
    🟢 发行商 获取成功！(attackers)
     ↳ ##### 
    🟢 预告片 获取成功！(attackers)
     ↳ https://cc3001.dmm.co.jp/litevideo/freepv/a/ati/#####/#####_dm_w.mp4 

    🙋🏻‍ 标题 
    ====================================
    🌐 来源优先级：airav_cc -> iqqtv -> avsex -> lulubar -> attackers -> airav_cc -> iqqtv -> avsex -> javbus -> freejavbt -> jav321
    🔴 airav_cc (失败)
    🔴 iqqtv (失败)
    🔴 avsex (失败)
    🔴 lulubar (失败)
    🟢 attackers (成功)
     ↳ #####

    🙋🏻‍ 原标题 
    ====================================
    🌐 来源优先级：attackers -> airav_cc -> iqqtv -> avsex -> javbus -> freejavbt -> jav321 -> lulubar
    🟢 attackers (成功)
     ↳ #####

    🙋🏻‍ 简介 
    ====================================
    🌐 来源优先级：airav_cc -> avsex -> iqqtv -> lulubar -> attackers -> airav_cc -> avsex -> iqqtv -> lulubar -> jav321
    🔴 airav_cc (失败)
    🔴 avsex (失败)
    🔴 iqqtv (失败)
    🔴 lulubar (失败)
    🟢 attackers (成功)
     ↳ #####。

    🙋🏻‍ 原简介 
    ====================================
    🌐 来源优先级：attackers -> airav_cc -> avsex -> iqqtv -> lulubar -> jav321
    🟢 attackers (成功)
     ↳ #####。

    🙋🏻‍ 演员 
    ====================================
    🌐 来源优先级：attackers -> javbus -> airav_cc -> iqqtv -> avsex -> freejavbt -> jav321 -> lulubar
    🟢 attackers (成功)
     ↳ #####

    🙋🏻‍ 背景图 
    ====================================
    🌐 来源优先级：attackers -> javbus -> airav_cc -> iqqtv -> avsex -> freejavbt -> jav321 -> lulubar
    🟢 attackers (成功)
     ↳ https://cdn.up-timely.com/image/15/content/#####/#####_2.jpg

    🙋🏻‍ 封面图 
    ====================================
    🌐 来源优先级：attackers -> avsex -> javbus -> airav_cc -> freejavbt -> jav321
    🟢 attackers (成功)
     ↳ https://cdn.up-timely.com/image/15/content/#####/#####_1.jpg

    🙋🏻‍ 剧照 
    ====================================
    🌐 来源优先级：attackers -> javbus -> freejavbt -> jav321
    🟢 attackers (成功)
     ↳ ['https://cdn.up-timely.com/image/15/content/#####/#####_3.jpg', 'https://cdn.up-timely.com/image/15/content/#####/#####_4.jpg', 'https://cdn.up-timely.com/image/15/content/#####/#####_5.jpg', 'https://cdn.up-timely.com/image/15/content/#####/#####_6.jpg', 'https://cdn.up-timely.com/image/15/content/#####/#####_7.jpg', 'https://cdn.up-timely.com/image/15/content/#####/#####_8.jpg', 'https://cdn.up-timely.com/image/15/content/#####/#####_9.jpg', 'https://cdn.up-timely.com/image/15/content/#####/#####_10.jpg', 'https://cdn.up-timely.com/image/15/content/#####/#####_11.jpg', 'https://cdn.up-timely.com/image/15/content/#####/#####_12.jpg', 'https://cdn.up-timely.com/image/15/content/#####/#####_13.jpg', 'https://cdn.up-timely.com/image/15/content/#####/#####_14.jpg']

    🙋🏻‍ 标签 
    ====================================
    🌐 来源优先级：attackers -> javbus -> freejavbt -> airav_cc -> iqqtv -> avsex -> jav321 -> lulubar
    🟢 attackers (成功)
     ↳ #####

    🙋🏻‍ 发行日期 
    ====================================
    🌐 来源优先级：attackers -> javbus -> freejavbt -> airav_cc -> iqqtv -> avsex -> jav321 -> lulubar
    🟢 attackers (成功)
     ↳ 2021-9-7

    🙋🏻‍ 时长 
    ====================================
    🌐 来源优先级：attackers -> javbus -> freejavbt -> iqqtv -> avsex -> jav321
    🟢 attackers (成功)
     ↳ 130

    🙋🏻‍ 评分 
    ====================================
    🌐 来源优先级：jav321 -> freejavbt
    🟢 jav321 (成功)
     ↳ 4.0

    🙋🏻‍ 导演 
    ====================================
    🌐 来源优先级：attackers -> javbus -> freejavbt
    🟢 attackers (成功)
     ↳ #####

    🙋🏻‍ 系列 
    ====================================
    🌐 来源优先级：attackers -> javbus -> freejavbt -> jav321
    🔴 attackers (失败)
    🔴 javbus (失败)
    🔴 freejavbt (失败)
    🔴 jav321 (失败)

    🙋🏻‍ 片商 
    ====================================
    🌐 来源优先级：attackers -> javbus -> freejavbt -> airav_cc -> iqqtv -> jav321 -> lulubar
    🔴 attackers (失败)
    🟢 javbus (成功)
     ↳ アタッカーズ

    🙋🏻‍ 发行商 
    ====================================
    🌐 来源优先级：attackers -> javbus -> freejavbt -> jav321
    🟢 attackers (成功)
     ↳ #####

    🙋🏻‍ 预告片 
    ====================================
    🌐 来源优先级：attackers -> freejavbt
    🟢 attackers (成功)
     ↳ https://cc3001.dmm.co.jp/litevideo/freepv/a/ati/#####/#####_dm_w.mp4
 🌐 [website] attackers(4s) -> airav_cc[zh_cn](2s) -> iqqtv[jp](1s) -> avsex(1s) -> lulubar(2s) -> jav321(1s) -> javbus(1s) -> freejavbt(1s)
     title        : attackers (jp)
     originaltitle: attackers (jp)
     outline      : attackers (jp)
     originalplot : attackers (jp)
     actor        : attackers (jp)
     cover        : attackers (jp)
     poster       : attackers (jp)
     extrafanart  : attackers (jp)
     tag          : attackers (jp)
     release      : attackers (jp)
     runtime      : attackers (jp)
     score        : jav321 (jp)
     director     : attackers (jp)
     series       : ----- (not found)
     studio       : javbus (jp)
     publisher    : attackers (jp)
     trailer      : attackers (jp)
 🍀 Data done!(13s)
 🌸 Sehua title done!(0s)
 🔴 Translation failed!(Deepl)(3s) Error: 网页接口请求失败! 错误：429 Client Error:  for url: https://www2.deepl.com/jsonrpc
 🍀 Translation done!(Google)(4s)
     number       : #####
     letters      : #####
     has_sub      : #####
     mosaic       : 无码流出
     title        : #####
     originaltitle: #####
     actor        : #####
     outline      : #####
     originalplot : #####
     tag          : #####
     release      : #####
     year         : #####
     runtime      : #####
     score        : 4.0
     director     : #####
     studio       : アタッカーズ
     publisher    : #####
     trailer      : https://cc3001.dmm.co.jp/litevideo/freepv/a/ati/#####/#####_dm_w.mp4
     website      : https://attackers.net/works/detail/#####
 🍀 Folder done! (new)
 🖼 HD Thumb found! (Google(sun9-21.userapi.com))(9s)
 🍀 Thumb done! (Google(sun9-21.userapi.com))(13s) 
 🍀 Fanart done! (copy thumb)(0s)
 🍀 Poster done! (thumb right)(0s)
 🍀 Thumb add watermark: 字幕,流出!
 🍀 Poster add watermark: 字幕,流出!
 🍀 ExtraFanart done! (attackers 12/12)(3s)
 🍀 Nfo done! (new)(0s)
 🔴 Failed to move movie file to success folder!
     Move File: /Volumes/#####/未整理/test bug/#####-C.mp4
 To: /Volumes/#####/未整理/test bug/#####/#####-C ##### #####/未知系列 #####-C ##### #####.mp4 
 Error: [Errno 2] No such file or directory: '/Volumes/#####/未整理/test bug/#####-C.mp4'
Traceback (most recent call last):
  File "shutil.py", line 825, in move
FileNotFoundError: [Errno 2] No such file or directory: '/Volumes/#####/未整理/test bug/#####-C.mp4' -> '/Volumes/#####/未整理/test bug/#####/#####-C ##### #####/未知系列 #####-C ##### #####.mp4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "models/base/file.py", line 32, in move_file
  File "shutil.py", line 845, in move
  File "shutil.py", line 444, in copy2
  File "shutil.py", line 264, in copyfile
FileNotFoundError: [Errno 2] No such file or directory: '/Volumes/#####/未整理/test bug/#####-C.mp4'


 🔴 Move file to the failed folder!
 🙊 [Movie] /Volumes/#####/未整理/test bug/failed/#####-C.mp4
================================================================================
 🕷 11:25:57 1/2 #####-C.mp4 刮削完成！用时 40 秒！
 🕷 剩余正在刮削的线程：1
 🏖 已累计刮削 1/2，已连续刮削 1/10...

2/2 (100.00%) round(1) #####-C.mp4
================================================================================
 🙈 [Movie] /Volumes/#####/未整理/test bug/#####-C.mp4
 🚘 [Number] #####
 🌐 [website] attackers(5s) -> airav_cc[zh_cn](5s) -> iqqtv[jp](2s) -> avsex(3s) -> lulubar(2s) -> jav321(1s) -> javlibrary[jp](0s) -> javdb(8s) -> javbus(1s) -> freejavbt(1s)
    🌐 attackers
       搜索地址: https://attackers.net/search/list?keyword=##### 
       番号地址: https://attackers.net/works/detail/##### 
       数据获取成功！
    🟢 标题 获取成功！(attackers)
     ↳ #####…  
    🌐 airav[cn]
       搜索地址: https://airav.io/cn/searchresults.aspx?Search=#####&Type=0 
       搜索结果: 未匹配到番号！ 
    🌐 iqqtv[jp]
       搜索地址: https://iqq5.xyz/jp/search.php?kw=##### 
       搜索结果: 未匹配到番号！ 
    🌐 avsex
       搜索地址: https://paycalling.com/tw/search?query=##### 
       网络请求错误: https://paycalling.com/tw/search?query=#####
Error: Failed to perform, ErrCode: 35, Reason: 'Recv failure: Connection reset by peer'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.  
    🌐 lulubar
       搜索地址: https://lulubar.co/video/bysearch?search=#####&page=1 
       网络请求错误: 403 https://lulubar.co/video/bysearch?search=#####&page=1 
    🔴 中文标题 获取失败！
    🟢 简介 获取成功！(attackers)
     ↳ #####  
    🔴 中文简介 获取失败！
    🟢 演员 获取成功！(attackers)
     ↳ 晶エリー 
    🟢 背景图 获取成功！(attackers)
     ↳ https://cdn.up-timely.com/image/15/content/#####/#####_2.jpg 
    🟢 封面图 获取成功！(attackers)
     ↳ https://cdn.up-timely.com/image/15/content/#####/#####_1.jpg 
    🟢 剧照 获取成功！(attackers)
     ↳ ['https://cdn.up-timely.com/image/15/content/#####/#####_3.jpg', 'https://cdn.up-timely.com/image/15/content/#####/#####_4.jpg', 'https://cdn.up-timely.com/image/15/content/#####/#####_5.jpg', 'https://cdn.up-timely.com/image/15/content/#####/#####_6.jpg', 'https://cdn.up-timely.com/image/15/content/#####/#####_7.jpg', 'https://cdn.up-timely.com/image/15/content/#####/#####_8.jpg', 'https://cdn.up-timely.com/image/15/content/#####/#####_9.jpg', 'https://cdn.up-timely.com/image/15/content/#####/#####_10.jpg', 'https://cdn.up-timely.com/image/15/content/#####/#####_11.jpg', 'https://cdn.up-timely.com/image/15/content/#####/#####_12.jpg', 'https://cdn.up-timely.com/image/15/content/#####/#####_13.jpg', 'https://cdn.up-timely.com/image/15/content/#####/#####_14.jpg'] 
    🟢 标签 获取成功！(attackers)
     ↳ #####
    🟢 发行日期 获取成功！(attackers)
     ↳ 2021-4-7 
    🟢 时长 获取成功！(attackers)
     ↳ #####  
    🌐 jav321
       搜索地址: https://www.jav321.com/search {"sn": #####}
       番号地址: https://www.jav321.com/video/##### 
       数据获取成功！ 
    🌐 javlibrary[jp]
       搜索地址: https://www.javlibrary.com/ja/vl_searchbyid.php?keyword=##### 
       请求错误: https://www.javlibrary.com/ja/vl_searchbyid.php?keyword=#####
Error: Failed to perform, ErrCode: 7, Reason: 'Failed to connect to www.javlibrary.com port 443 after 35 ms: Couldn't connect to server'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details. 
    🌐 javdb (⏱ 8S)
       搜索地址: https://www.javdb.com/search?q=#####&locale=zh 
       请求错误: https://www.javdb.com/search?q=#####&locale=zh
Error: Failed to perform, ErrCode: 7, Reason: 'Failed to connect to www.javdb.com port 443 after 12 ms: Couldn't connect to server'. This may be a libcurl error, See https://curl.se/libcurl/c/libcurl-errors.html first for more details.
    🔴 评分 获取失败！
    🟢 导演 获取成功！(attackers)
     ↳ #####  
    🌐 javbus
       番号地址: https://www.javbus.com/##### 
       数据获取成功！
    🌐 freejavbt
       番号地址: https://freejavbt.com/##### 
       数据获取失败: 番号标题不存在！
    🔴 系列 获取失败！
    🟢 片商 获取成功！(javbus)
     ↳ アタッカーズ 
    🟢 发行商 获取成功！(attackers)
     ↳ ##### 
    🟢 预告片 获取成功！(attackers)
     ↳ https://cc3001.dmm.co.jp/litevideo/freepv/a/ati/#####/#####_dm_w.mp4 

    🙋🏻‍ 标题 
    ====================================
    🌐 来源优先级：airav_cc -> iqqtv -> avsex -> lulubar -> attackers -> airav_cc -> iqqtv -> avsex -> javbus -> freejavbt -> jav321 -> javlibrary -> javdb
    🔴 airav_cc (失败)
    🔴 iqqtv (失败)
    🔴 avsex (失败)
    🔴 lulubar (失败)
    🟢 attackers (成功)
     ↳ #####…

    🙋🏻‍ 原标题 
    ====================================
    🌐 来源优先级：attackers -> airav_cc -> iqqtv -> avsex -> javbus -> freejavbt -> jav321 -> javlibrary -> javdb -> lulubar
    🟢 attackers (成功)
     ↳ #####…

    🙋🏻‍ 简介 
    ====================================
    🌐 来源优先级：airav_cc -> avsex -> iqqtv -> lulubar -> attackers -> airav_cc -> avsex -> iqqtv -> lulubar -> jav321
    🔴 airav_cc (失败)
    🔴 avsex (失败)
    🔴 iqqtv (失败)
    🔴 lulubar (失败)
    🟢 attackers (成功)
     ↳ #####
    🙋🏻‍ 原简介 
    ====================================
    🌐 来源优先级：attackers -> airav_cc -> avsex -> iqqtv -> lulubar -> jav321
    🟢 attackers (成功)
     ↳ #####
    🙋🏻‍ 演员 
    ====================================
    🌐 来源优先级：attackers -> javbus -> javlibrary -> javdb -> airav_cc -> iqqtv -> avsex -> freejavbt -> jav321 -> lulubar
    🟢 attackers (成功)
     ↳ 晶エリー

    🙋🏻‍ 背景图 
    ====================================
    🌐 来源优先级：attackers -> javbus -> airav_cc -> iqqtv -> avsex -> freejavbt -> jav321 -> javlibrary -> javdb -> lulubar
    🟢 attackers (成功)
     ↳ https://cdn.up-timely.com/image/15/content/#####/#####_2.jpg

    🙋🏻‍ 封面图 
    ====================================
    🌐 来源优先级：attackers -> avsex -> javbus -> airav_cc -> freejavbt -> jav321 -> javdb
    🟢 attackers (成功)
     ↳ https://cdn.up-timely.com/image/15/content/#####/#####_1.jpg

    🙋🏻‍ 剧照 
    ====================================
    🌐 来源优先级：attackers -> javbus -> freejavbt -> jav321 -> javdb
    🟢 attackers (成功)
     ↳ ['https://cdn.up-timely.com/image/15/content/#####/#####_3.jpg', 'https://cdn.up-timely.com/image/15/content/#####/#####_4.jpg', 'https://cdn.up-timely.com/image/15/content/#####/#####_5.jpg', 'https://cdn.up-timely.com/image/15/content/#####/#####_6.jpg', 'https://cdn.up-timely.com/image/15/content/#####/#####_7.jpg', 'https://cdn.up-timely.com/image/15/content/#####/#####_8.jpg', 'https://cdn.up-timely.com/image/15/content/#####/#####_9.jpg', 'https://cdn.up-timely.com/image/15/content/#####/#####_10.jpg', 'https://cdn.up-timely.com/image/15/content/#####/#####_11.jpg', 'https://cdn.up-timely.com/image/15/content/#####/#####_12.jpg', 'https://cdn.up-timely.com/image/15/content/#####/#####_13.jpg', 'https://cdn.up-timely.com/image/15/content/#####/#####_14.jpg']

    🙋🏻‍ 标签 
    ====================================
    🌐 来源优先级：attackers -> javbus -> freejavbt -> airav_cc -> iqqtv -> avsex -> jav321 -> javlibrary -> javdb -> lulubar
    🟢 attackers (成功)
     ↳ #####

    🙋🏻‍ 发行日期 
    ====================================
    🌐 来源优先级：attackers -> javbus -> freejavbt -> airav_cc -> iqqtv -> avsex -> jav321 -> javlibrary -> javdb -> lulubar
    🟢 attackers (成功)
     ↳ 2021-4-7

    🙋🏻‍ 时长 
    ====================================
    🌐 来源优先级：attackers -> javbus -> freejavbt -> iqqtv -> avsex -> jav321 -> javlibrary -> javdb
    🟢 attackers (成功)
     ↳ #####

    🙋🏻‍ 评分 
    ====================================
    🌐 来源优先级：jav321 -> javlibrary -> javdb -> freejavbt
    🔴 jav321 (失败)
    🔴 javlibrary (失败)
    🔴 javdb (失败)
    🔴 freejavbt (失败)

    🙋🏻‍ 导演 
    ====================================
    🌐 来源优先级：attackers -> javbus -> freejavbt -> javlibrary -> javdb
    🟢 attackers (成功)
     ↳ #####

    🙋🏻‍ 系列 
    ====================================
    🌐 来源优先级：attackers -> javbus -> freejavbt -> jav321 -> javdb
    🔴 attackers (失败)
    🔴 javbus (失败)
    🔴 freejavbt (失败)
    🔴 jav321 (失败)
    🔴 javdb (失败)

    🙋🏻‍ 片商 
    ====================================
    🌐 来源优先级：attackers -> javbus -> freejavbt -> airav_cc -> iqqtv -> jav321 -> javlibrary -> javdb -> lulubar
    🔴 attackers (失败)
    🟢 javbus (成功)
     ↳ アタッカーズ

    🙋🏻‍ 发行商 
    ====================================
    🌐 来源优先级：attackers -> javbus -> freejavbt -> jav321 -> javlibrary -> javdb
    🟢 attackers (成功)
     ↳ #####

    🙋🏻‍ 预告片 
    ====================================
    🌐 来源优先级：attackers -> freejavbt
    🟢 attackers (成功)
     ↳ https://cc3001.dmm.co.jp/litevideo/freepv/a/ati/#####/#####_dm_w.mp4

    🙋🏻‍ 想看人数 
    ====================================
    🌐 来源优先级：javlibrary -> javdb
    🔴 javlibrary (失败)
    🔴 javdb (失败)
 🌐 [website] attackers(5s) -> airav_cc[zh_cn](5s) -> iqqtv[jp](2s) -> avsex(3s) -> lulubar(2s) -> jav321(1s) -> javlibrary[jp](0s) -> javdb(8s) -> javbus(1s) -> freejavbt(1s)
     title        : attackers (jp)
     originaltitle: attackers (jp)
     outline      : attackers (jp)
     originalplot : attackers (jp)
     actor        : attackers (jp)
     cover        : attackers (jp)
     poster       : attackers (jp)
     extrafanart  : attackers (jp)
     tag          : attackers (jp)
     release      : attackers (jp)
     runtime      : attackers (jp)
     score        : ----- (not found)
     director     : attackers (jp)
     series       : ----- (not found)
     studio       : javbus (jp)
     publisher    : attackers (jp)
     trailer      : attackers (jp)
     wanted       : ----- (not found)
 🍀 Data done!(28s)
 🌸 Sehua title done!(0s)
 🔴 Translation failed!(Deepl)(2s) Error: 网页接口请求失败! 错误：429 Client Error:  for url: https://www2.deepl.com/jsonrpc
 🔴 Translation failed!(Youdao)(2s) Error: 返回数据未找到翻译结果！返回内容：{'errorCode': 50}
 🍀 Translation done!(Google)(2s)
     number       : #####
     letters      : #####
     has_sub      : #####
     mosaic       : 无码流出
     title        : #####
     originaltitle: #####…
     actor        : #####
     outline      : #####
     originalplot : #####
     tag          : #####，发行: #####
     release      : #####
     year         : 2021
     runtime      : #####
     director     : #####
     studio       : #####
     publisher    : #####
     trailer      : https://cc3001.dmm.co.jp/litevideo/freepv/a/ati/#####/#####_dm_w.mp4
     website      : https://attackers.net/works/detail/#####
 🍀 Folder done! (new)
 🖼 HD Thumb found! (Google(img.javpop.mov))(9s)
 🍀 Thumb done! (Google(img.javpop.mov))(11s) 
 🍀 Fanart done! (copy thumb)(0s)
 🍀 Poster done! (thumb right)(0s)
 🍀 Thumb add watermark: 字幕,流出!
 🍀 Poster add watermark: 字幕,流出!
 🍀 ExtraFanart done! (attackers 12/12)(3s)
 🍀 Nfo done! (new)(0s)
 🔴 Failed to move movie file to success folder!
     Move File: /Volumes/#####/未整理/test bug/#####-C.mp4
 To: /Volumes/#####/未整理/test bug/#####/#####-C #####… #####/未知系列 #####-C #####… #####.mp4 
 Error: [Errno 2] No such file or directory: '/Volumes/#####/未整理/test bug/#####-C.mp4'
Traceback (most recent call last):
  File "shutil.py", line 825, in move
FileNotFoundError: [Errno 2] No such file or directory: '/Volumes/#####/未整理/test bug/#####-C.mp4' -> '/Volumes/#####/未整理/test bug/#####/#####-C #####… #####/未知系列 #####-C #####… #####.mp4'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "models/base/file.py", line 32, in move_file
  File "shutil.py", line 845, in move
  File "shutil.py", line 444, in copy2
  File "shutil.py", line 264, in copyfile
FileNotFoundError: [Errno 2] No such file or directory: '/Volumes/#####/未整理/test bug/#####-C.mp4'


 🔴 Move file to the failed folder!
 🙊 [Movie] /Volumes/#####/未整理/test bug/failed/#####-C.mp4
================================================================================
 🕷 11:25:59 2/2 #####-C.mp4 刮削完成！用时 51 秒！
 🕷 剩余正在刮削的线程：0
 🏖 已累计刮削 2/2，已连续刮削 2/10...
================================================================================
 ⏳ Cleaning empty folders...
 🗑 Clean empty folder: /Volumes/#####/未整理/test bug/failed
 🍀 Clean done!(0s)
================================================================================
 🎉🎉🎉 All finished!!! Total 2 , Success 0 , Failed 2 
================================================================================
    *** Failed results ****
 🔴 1 /Volumes/#####/未整理/test bug/failed/#####-C.mp4
    
================================================================================
 🔴 2 /Volumes/#####/未整理/test bug/failed/#####-C.mp4
    
================================================================================
 ⏰ Start time  : 2024-07-15 11:25:09
 🏁 End time    : 2024-07-15 11:25:59
 ⏱ Used time   : 50.63S
 📺 Movies num  : 2
 🍕 Per time    : 25.31S
================================================================================
```

### 截图

<img width="1033" alt="截屏2024-07-15 上午11 27 46" src="https://github.com/user-attachments/assets/d7cc9dc6-55dd-45e4-89f7-15833518921c">
<img width="728" alt="截屏2024-07-15 上午11 31 05" src="https://github.com/user-attachments/assets/7bff1a6f-829f-419c-9f68-b6995ffed168">
<img width="1034" alt="截屏2024-07-15 上午11 46 02" src="https://github.com/user-attachments/assets/fe9f4681-f0a3-4624-be04-2719a92f741b">

**Comment by sqzw-x** [comment]
`shutil` 移动文件出错，报告源文件不存在
Windows 上不存在此问题，应该和 Mac 文件系统相关

**Comment by sqzw-x** [comment]
#224
