### ISSUE TITLE
无法运行

### ISSUE THREAD

**Issue by Snarl3908** [sqzw-x/mdcx#304]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备

### 你使用版本的 commit hash

f5b42615

### 描述你的问题

运行程序提示如下错误：

Traceback (most recent call last):
  File "main.py", line 13, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "controllers\main_window\main_window.py", line 13, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "controllers\cut_window.py", line 12, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "models\core\scraper.py", line 15, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "models\core\crawler.py", line 12, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "models\crawlers\getchu_dmm.py", line 6, in <module>
ImportError: cannot import name 'dmm' from 'models.crawlers' (unknown location)

### 如何复现

直接运行就报错

### 预期行为

修复错误

### 相关 Logs

```Text
Traceback (most recent call last):
  File "main.py", line 13, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "controllers\main_window\main_window.py", line 13, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "controllers\cut_window.py", line 12, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "models\core\scraper.py", line 15, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "models\core\crawler.py", line 12, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "models\crawlers\getchu_dmm.py", line 6, in <module>
ImportError: cannot import name 'dmm' from 'models.crawlers' (unknown location)
```

### 截图

![圖片](https://github.com/user-attachments/assets/d3e3c910-f837-4737-acf8-9f9ac94cdd8d)

### 还有别的吗？

NULL

**Comment by xayane** [comment]
+1
同样的报错，用的是今天的daily-release版本。

**Comment by pandoraaab** [comment]
+1
最新的daily-release版本无法运行

**Comment by epubc** [comment]
I fixed the error by uncomment at line 644 in **dmm.py** file and repacking

**Comment by saikishi** [comment]
+1

**Comment by a525850194** [comment]
> 我已经提交修复的PR了: #305 ，急需的可以先到我的构建里下载修复版: https://github.com/northsea4/mdcx/releases/tag/daily_release

可以运行，感谢
