### ISSUE TITLE
程序打开错误

### ISSUE THREAD

**Issue by htyxyt** [sqzw-x/mdcx#313]
### 在提问之前...

- [X] 我已经搜索了现有的 issues
- [X] 我在提问题之前至少花费了 5 分钟来思考和准备

### 你使用版本的 commit hash

MDCx-daily_release-windows-x86_64-f5b42615

### 描述你的问题

打开exe的时候就报这个错误
Failed to execute script 'main' due to unhandled exception:
 cannot import name 'dmm' from 'models.crawlers'

### 如何复现

1. 前往 '...'
2. 点击 '....'
3. 滑动到 '....'
4. 出现问题

### 相关 Logs

```Text
Traceback (most recent call last):
  File "main.py", line 13, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "controllers\main_window\main_window.py", line 13, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "controllers\cut_window.py", line 12, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "models\core\scraper.py", line 15, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "models\core\crawler.py", line 12, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "models\crawlers\getchu_dmm.py", line 6, in <module>
ImportError: cannot import name 'dmm' from 'models.crawlers' (unknown location)
```

### 截图

![image](https://github.com/user-attachments/assets/5768adf6-a480-4892-b171-8bebcf7ca83d)

**Comment by htyxyt** [comment]
https://github.com/sqzw-x/mdcx/issues/304 一样的问题，我提交重复了

**Comment by smart0114** [comment]
我也是一样的问题
